# Generated by Django 6.0.2 on 2026-02-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='recruiter.company'),
        ),
    ]
