# Generated by Django 6.0.2 on 2026-02-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company'),
        ('recruiter', '0003_alter_recruiterprofile_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='company.company'),
        ),
    ]
